In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('train.csv')

In [3]:
data.shape

(42000, 785)

In [4]:
data.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
pixel6      0
pixel7      0
pixel8      0
pixel9      0
pixel10     0
pixel11     0
pixel12     0
pixel13     0
pixel14     0
pixel15     0
pixel16     0
pixel17     0
pixel18     0
pixel19     0
pixel20     0
pixel21     0
pixel22     0
pixel23     0
pixel24     0
pixel25     0
pixel26     0
pixel27     0
pixel28     0
           ..
pixel754    0
pixel755    0
pixel756    0
pixel757    0
pixel758    0
pixel759    0
pixel760    0
pixel761    0
pixel762    0
pixel763    0
pixel764    0
pixel765    0
pixel766    0
pixel767    0
pixel768    0
pixel769    0
pixel770    0
pixel771    0
pixel772    0
pixel773    0
pixel774    0
pixel775    0
pixel776    0
pixel777    0
pixel778    0
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [5]:
data.pixel2.value_counts()

0    42000
Name: pixel2, dtype: int64

In [6]:
data.label.value_counts()

1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: label, dtype: int64

## PCA implementation

In [46]:
from sklearn.decomposition import PCA

In [47]:
pc=PCA(n_components=.99)

In [107]:
x=pc.fit_transform(data.drop(['label'],axis=1))

In [108]:
pc.n_components_

331

In [109]:
x.shape

(42000, 331)

In [7]:
from sklearn.model_selection import train_test_split

In [51]:
xtr,xte,ytr,yte=train_test_split(x,data.label,test_size=.20,random_state=1)

In [52]:
xtr.shape,xte.shape

((33600, 331), (8400, 331))

In [53]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

In [54]:
from sklearn.metrics import accuracy_score, r2_score,confusion_matrix

In [55]:
lr=LogisticRegression(C=1)

In [56]:
svm=SVC()

In [57]:
rd=RandomForestClassifier()

In [58]:
dt=DecisionTreeClassifier()

## Logistics regression

In [59]:
lr.fit(xtr,ytr)

D:\Program Files\ANACONDA\lib\site-packages\sklearn\linear_model\_logistic.py:939: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html.
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [60]:
pred_lr=lr.predict(xte)

In [61]:
lr.score(xte,yte)

0.9134523809523809

In [62]:
score_lr=pd.DataFrame([["Logistics Regression",accuracy_score(yte,pred_lr),r2_score(yte,pred_lr),confusion_matrix(yte,pred_lr)]])

In [63]:
score_lr.columns=['model','accuracy score','r2_score','confusion matrix']

In [64]:
score_lr

model  accuracy score  r2_score  \
0  Logistics Regression        0.913452  0.826239   

                                    confusion matrix  
0  [[815, 0, 4, 1, 3, 11, 14, 1, 3, 1], [0, 911, ...

In [65]:
confusion_matrix(yte,pred_lr)

array([[815,   0,   4,   1,   3,  11,  14,   1,   3,   1],
       [  0, 911,   3,   7,   0,   2,   4,   1,  11,   1],
       [  8,  10, 764,  11,   6,   4,   6,  10,  14,   2],
       [  3,   4,  23, 774,   0,  32,   2,  10,  16,   9],
       [  2,   4,   6,   0, 769,   1,   6,   3,   5,  33],
       [ 15,   4,   4,  26,   9, 630,  14,   8,  17,   4],
       [  7,   1,   2,   0,  10,  11, 766,   1,   1,   1],
       [  0,   4,   9,   5,   8,   0,   0, 783,   2,  39],
       [ 10,  22,  11,  31,   9,  27,   7,   2, 714,  13],
       [  3,   5,   2,   6,  32,   6,   0,  32,  10, 747]], dtype=int64)

## SVM

In [136]:
svm=SVC(C=10,gamma=.01)

In [137]:
svm.fit(xtr,ytr)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
pred_svm=svm.predict(xte)

In [68]:
svm.score(xte,yte)

0.9796428571428571

In [ ]:
svm.score(xte,yte)

In [ ]:
score_svm=pd.DataFrame([["SVM",accuracy_score(yte,pred_svm),r2_score(yte,pred_svm),confusion_matrix(yte,pred_svm)]])

In [133]:
score_svm.columns=['model','accuracy score','r2_score','confusion matrix']

In [ ]:
score_svm

In [71]:
score_svm

model  accuracy score  r2_score  \
0   SVM        0.979643  0.959593   

                                    confusion matrix  
0  [[847, 0, 2, 0, 0, 1, 3, 0, 0, 0], [0, 934, 2,...

In [72]:
confusion_matrix(yte,pred_svm)

array([[847,   0,   2,   0,   0,   1,   3,   0,   0,   0],
       [  0, 934,   2,   2,   0,   0,   1,   0,   1,   0],
       [  1,   1, 820,   1,   1,   0,   2,   5,   4,   0],
       [  0,   0,   8, 843,   1,  10,   0,   4,   4,   3],
       [  0,   1,   2,   0, 810,   0,   1,   4,   0,  11],
       [  2,   0,   0,   8,   0, 715,   3,   0,   1,   2],
       [  2,   0,   1,   0,   3,   3, 790,   0,   1,   0],
       [  0,   2,   4,   0,   3,   0,   0, 832,   0,   9],
       [  1,   5,   1,   1,   4,   5,   3,   1, 822,   3],
       [  3,   1,   0,   2,  11,   2,   0,   6,   2, 816]], dtype=int64)

## Desicion Tree

In [73]:
dt.fit(xtr,ytr)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [74]:
pred_dt=dt.predict(xte)

In [75]:
dt.score(xte,yte)

0.8067857142857143

In [76]:
score_dt=pd.DataFrame([["Desicion Tree",accuracy_score(yte,pred_dt),r2_score(yte,pred_dt),confusion_matrix(yte,pred_dt)]])

In [77]:
score_dt.columns=['model','accuracy score','r2_score','confusion matrix']

In [78]:
score_dt

model  accuracy score  r2_score  \
0  Desicion Tree        0.806786  0.644266   

                                    confusion matrix  
0  [[757, 0, 18, 9, 6, 19, 14, 9, 10, 11], [0, 89...

In [79]:
confusion_matrix(yte,pred_dt)

array([[757,   0,  18,   9,   6,  19,  14,   9,  10,  11],
       [  0, 890,  12,   5,   5,   4,   4,  10,   8,   2],
       [ 10,  12, 676,  24,  17,  17,  25,  19,  27,   8],
       [ 14,   5,  31, 663,  11,  64,  12,   9,  51,  13],
       [  8,   3,  14,   8, 634,  22,  14,  27,  15,  84],
       [ 15,   2,  13,  66,  23, 509,  30,  17,  34,  22],
       [ 25,   5,  15,   7,  19,  25, 687,   2,   9,   6],
       [  0,   7,  16,   9,  19,   7,   2, 727,  13,  50],
       [ 10,   9,  37,  48,  19,  64,  10,  13, 613,  23],
       [  6,   1,  10,  15,  82,  13,   5,  66,  24, 621]], dtype=int64)

 ## Random Forest

In [121]:
rd=RandomForestClassifier(criterion='gini')

In [122]:
rd.fit(xtr,ytr)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [123]:
pred_rd=rd.predict(xte)

In [124]:
rd.score(xte,yte)

0.9329761904761905

In [125]:
score_rd=pd.DataFrame([["Random forest",accuracy_score(yte,pred_dt),r2_score(yte,pred_rd),confusion_matrix(yte,pred_rd)]])

In [126]:
score_rd.columns=['model','accuracy score','r2_score','confusion matrix']

In [127]:
score_rd

model  accuracy score  r2_score  \
0  Random forest        0.806786  0.866152   

                                    confusion matrix  
0  [[831, 0, 6, 1, 1, 4, 8, 0, 2, 0], [0, 918, 6,...

In [88]:
confusion_matrix(yte,pred_rd)

array([[830,   0,   7,   1,   1,   2,   9,   0,   3,   0],
       [  1, 921,   6,   6,   0,   2,   2,   0,   2,   0],
       [  8,   1, 777,  12,   5,   0,   5,   8,  18,   1],
       [  3,   0,  16, 804,   3,  18,   4,   6,  14,   5],
       [  0,   2,   3,   1, 773,   0,   9,   4,   1,  36],
       [  8,   0,   1,  27,   6, 667,  10,   6,   1,   5],
       [  6,   0,   3,   0,   4,   9, 776,   0,   2,   0],
       [  1,   4,  14,   3,   7,   0,   0, 803,   1,  17],
       [  3,   8,  12,  40,   8,  21,   2,   1, 741,  10],
       [  6,   2,   3,  11,  30,   4,   2,  28,  10, 747]], dtype=int64)

In [93]:
confusion_matrix(yte,pred_svm)

array([[847,   0,   2,   0,   0,   1,   3,   0,   0,   0],
       [  0, 934,   2,   2,   0,   0,   1,   0,   1,   0],
       [  1,   1, 820,   1,   1,   0,   2,   5,   4,   0],
       [  0,   0,   8, 843,   1,  10,   0,   4,   4,   3],
       [  0,   1,   2,   0, 810,   0,   1,   4,   0,  11],
       [  2,   0,   0,   8,   0, 715,   3,   0,   1,   2],
       [  2,   0,   1,   0,   3,   3, 790,   0,   1,   0],
       [  0,   2,   4,   0,   3,   0,   0, 832,   0,   9],
       [  1,   5,   1,   1,   4,   5,   3,   1, 822,   3],
       [  3,   1,   0,   2,  11,   2,   0,   6,   2, 816]], dtype=int64)

In [90]:
score_pca=pd.concat([score_lr,score_svm,score_dt,score_rd],axis=0)

In [ ]:
#score_std.columns=['model','accuracy score','r2_score','f1_score','precision_score','recall score','roc_auc_score','confusion matrix']

In [91]:
score_pca

model  accuracy score  r2_score  \
0  Logistics Regression        0.913452  0.826239   
0                   SVM        0.979643  0.959593   
0         Desicion Tree        0.806786  0.644266   
0         Random forest        0.806786  0.864558   

                                    confusion matrix  
0  [[815, 0, 4, 1, 3, 11, 14, 1, 3, 1], [0, 911, ...  
0  [[847, 0, 2, 0, 0, 1, 3, 0, 0, 0], [0, 934, 2,...  
0  [[757, 0, 18, 9, 6, 19, 14, 9, 10, 11], [0, 89...  
0  [[830, 0, 7, 1, 1, 2, 9, 0, 3, 0], [1, 921, 6,...

In [92]:
score

model  accuracy score  r2_score  \
0  Logistics Regression        0.921548  0.847232   
0                   SVM        0.978095  0.954316   
0         Desicion Tree        0.858095  0.714400   
0         Random forest        0.858095  0.929796   

                                    confusion matrix  
0  [[824, 0, 3, 1, 3, 5, 12, 2, 2, 1], [0, 917, 5...  
0  [[847, 0, 0, 0, 1, 2, 3, 0, 0, 0], [0, 934, 1,...  
0  [[776, 3, 12, 6, 5, 18, 16, 7, 6, 4], [1, 892,...  
0  [[844, 0, 3, 0, 1, 1, 2, 1, 1, 0], [0, 925, 6,...

In [94]:
test=pd.read_csv('test.csv')

In [95]:
test.shape

(28000, 784)

In [96]:
test.isnull().sum()

pixel0      0
pixel1      0
pixel2      0
pixel3      0
pixel4      0
pixel5      0
pixel6      0
pixel7      0
pixel8      0
pixel9      0
pixel10     0
pixel11     0
pixel12     0
pixel13     0
pixel14     0
pixel15     0
pixel16     0
pixel17     0
pixel18     0
pixel19     0
pixel20     0
pixel21     0
pixel22     0
pixel23     0
pixel24     0
pixel25     0
pixel26     0
pixel27     0
pixel28     0
pixel29     0
           ..
pixel754    0
pixel755    0
pixel756    0
pixel757    0
pixel758    0
pixel759    0
pixel760    0
pixel761    0
pixel762    0
pixel763    0
pixel764    0
pixel765    0
pixel766    0
pixel767    0
pixel768    0
pixel769    0
pixel770    0
pixel771    0
pixel772    0
pixel773    0
pixel774    0
pixel775    0
pixel776    0
pixel777    0
pixel778    0
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 784, dtype: int64

In [110]:
te=pc.transform(test)

In [111]:
te.shape

(28000, 331)

In [113]:
pred=svm.predict(te)

In [117]:
pred=pd.DataFrame(pred)

In [120]:
pred.to_csv('result.csv')

In [119]:
pred.shape

(28000, 1)